### ISSUE TITLE
Add firebase dependencies in journalist app

### ISSUE THREAD

**Issue by tanmaydixit** [MobileApplicationsClub/DoJMA#100]
| Depencencies       needed                                      |  Name                         |
|                                                                           -- |                 --              |
|  com.google.firebase:firebase-core:16.0.0           | Analytics                 |
| com.google.firebase:firebase-database:16.0.1    | Realtime Database |
| com.google.firebase:firebase-storage:16.0.1       | Storage                   |
| com.google.firebase:firebase-messaging:17.0.0 | Cloud Messaging    |

**Comment by Rushi98** [comment]
isn't authentication needed?

**Comment by tanmaydixit** [comment]
Mostly no we could avoid(using firebase auth) by doing a pin/key login(they are easy to implement, easy to share and almost equally secure).

**Comment by Rushi98** [comment]
fixed by c3c5e3dc7505a94835474cbcbefa71078b1639b4
