### ISSUE TITLE
About MAC activity crashing

### ISSUE THREAD

**Issue by YashxD** [MobileApplicationsClub/DoJMA#105]
The About MAC activity can't be opened.
Error code: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.csatimes.dojma/com.csatimes.dojma.activities.AboutUsActivity}: android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class androidx.coordinatorlayout.widget.CoordinatorLayout

**Comment by tanmaydixit** [comment]
will be resolved with #98
