### ISSUE TITLE
Splash Screen is showing for every app launch

### ISSUE THREAD

**Issue by aryanagarwal15** [MobileApplicationsClub/DoJMA#117]
<img src="https://user-images.githubusercontent.com/28765515/41708254-b236b05e-755d-11e8-930b-6df02f0b05d9.png" width="250">

The Splash Screen is currently being shown every single time the app is launched.

As out app offers a lot of utility I believe this will hinder user experience.

The Splash screen should be shown only once when the app is launched for the first time.

**Comment by Rushi98** [comment]
If you look into the code, the splash screen is not an activity but a background for main activity. It is removed the moment main activity shows its content. This is done to replace the otherwise blank screen shown during the delay to launch main activity.

**Comment by aryanagarwal15** [comment]
@Rushi98 I believe the blank screen you are talking about should show a loading symbol (As per professional standards) instead of splash screen.

**Comment by Rushi98** [comment]
The splash screen is there in following apps in my smartphone:
1. AccuWeather
2. book my show
3. google calendar
4. google cloud console
5. google docs
6. google drive
7. google duo
8. edX
9. feedly
10. foodpanda
11. material gallery
12. geeksforgeeks
13. google maps
14. my idea app
15. google news
16. google photos
17. play books
18. play games
19. play music
20. google sheets
21. slack
22. google slides
23. swiggy
24. google tasks
25. tez
26. tnpsuite
27. unacademy
28. wikipedia
29. youtube
30. zomato
31. zoomcar

The rest of the apps either had blank / coloured screen or were loaded fast enough. 

NONE had a loading symbol.

**Comment by aryanagarwal15** [comment]
Oh ok. But can we atleast make the splash screen minimalist. Currently the created by Mobile App Club is a little too big for splash screen. We can probably reduce it's size.

**Comment by Rushi98** [comment]
I think it's better if we focus on issues at hand.

**Comment by aryanagarwal15** [comment]
ok!

**Comment by tanmaydixit** [comment]
I agree, its not a pressing matter.
And yes that splash screen will be changed soon.
