### ISSUE TITLE
Updated color scheme

### ISSUE THREAD

**Issue by aryanagarwal15** [MobileApplicationsClub/DoJMA#118]
<img src="https://user-images.githubusercontent.com/28765515/41734217-e94f609a-75a3-11e8-9b4a-c3bbd6e11e56.png" width="250">

Hey, This is what DoJMA's designers have designed as color scheme. they suggest doing a total white scheme with options for a dark mode (Which MAC graciously already has).

@tanmaydixit @Rushi98 I would like to know your views on this approach.

Please don't look at the middle recycler view design, they had the previous screenshots only to work with.
The left top most corner icon will reveal campus watch activity. And the DoJMA logo in between is just a placeholder, our designers are working vigilantly and will have a final design for dojma logo within a week.

If you guys approve I would like to implement it.

**Comment by Rushi98** [comment]
black and white scheme :heart: 
for campus watch, currently we have the icon on right side (visible only when new items are there), can be moved to left :+1: 
However, logo in top app bar is unheard/unseen anywhere

keeping on hold till final design is ready

**Comment by aryanagarwal15** [comment]
I would prefer to have campus watch icon to be on display forever, not just for new items. As we are going to build on campus watch for the whole year in here and nothing will be replaced.

**Comment by Rushi98** [comment]
It is designed to implement the _mark as read_ feature. One wouldn't want to see already read articles again and again. Also, one shouldn't miss out on articles just because he couldn't read them on time.

**Comment by aryanagarwal15** [comment]
I'm afraid that's not the requirement here. We do campus watch periodically and would like our reader to have access to it at all times, regardless he has read it or not. (Campus Watch majorly consist of very relevant and informative data that reader might come back to refer to)

**Comment by aryanagarwal15** [comment]
<img width="300" src="https://user-images.githubusercontent.com/28765515/43094428-7817c462-8ed0-11e8-995b-591aed72b1ba.jpeg">

Final Design
