### ISSUE TITLE
Bug in Article Viewer

### ISSUE THREAD

**Issue by aryanagarwal15** [MobileApplicationsClub/DoJMA#120]
**Issue:** 
In article images must be handled separately in ArticleViewerActivity. Currently the images shown are of actual length and are flowing out of bounds.

**Mimic the issue:** Search for "Runtastic Routes" article and scroll down to see in article images.

**Screenshot:**
<img src="https://user-images.githubusercontent.com/28765515/41811068-1636a59a-7726-11e8-913f-a2416cc93c5e.png" width="300">

**Comment by aryanagarwal15** [comment]
@Rushi98 Please allot this to me. I'll revamp the Article Activity all together.

**Comment by Rushi98** [comment]
How can this be solved? Showing images separately from text might not be a good idea as it would lose context. As can be demonstrated by the post in question itself.

**Comment by aryanagarwal15** [comment]
I am planning to apply advanced string manipulation techniques. Will just add a width attribute to image.

**Comment by Rushi98** [comment]
please explain (advanced string manipulation techniques)

**Comment by aryanagarwal15** [comment]
Basically here I have two methods to try out
1) Adding custom style attribute to each <img> tag. with correct width and padding.
2) Adding a custom style sheet to the html. With specific width for all the images.

**Comment by Rushi98** [comment]
how to do it on raw html?

**Comment by aryanagarwal15** [comment]
htmlData = "<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\" />" + htmlData;
// lets assume we have /assets/style.css file
webView.loadDataWithBaseURL("file:///android_asset/", htmlData, "text/html", "UTF-8", null);

**Comment by Rushi98** [comment]
The example post (http://bitsherald.org/api/get_post/?id=3412) has width and height as inline style. This will override the stylesheet attached.
Source: https://www.w3schools.com/css/css_howto.asp

**Comment by aryanagarwal15** [comment]
https://stackoverflow.com/questions/16813220/how-can-i-override-inline-styles-with-external-css

We can put !important in external css file for it to override inline style/width attributes.

**Comment by Rushi98** [comment]
fixed by #128
