### ISSUE TITLE
Notification for new campus watch

### ISSUE THREAD

**Issue by tanmaydixit** [MobileApplicationsClub/DoJMA#142]
Use firebase functions to send a notif.
Title: New Campus Watch available
Sub: [title of that campus watch]
on clicking of that campus watch if possible that campus watch should open(in the Campus Watch Activity)

**Comment by aryanagarwal15** [comment]
@aayushsingla Can we please complete this by this weekend itself. We have orientation next week, I really want people to experience campus watch before that!

**Comment by aryanagarwal15** [comment]
@aayushsingla I think the notification are not appearing to devices with Android 8.0+. Please run on emulator and check

**Comment by aayushsingla** [comment]
@aryanagarwal15 It's just a minor change.Will do it asap.

**Comment by aryanagarwal15** [comment]
@aayushsingla can you please do this today. I want a soft launch of this feature by tomorrow.

**Comment by aryanagarwal15** [comment]
@aayushsingla Did you make the required changes?

**Comment by aayushsingla** [comment]
@aryanagarwal15 changes done.Im facing difficulty in testing it.I will make a PR today with the changes I think. please test it and tell me if that works.

**Comment by aryanagarwal15** [comment]
@aayushsingla I tried the new pull request. That doesn't solve the problem. I have many users with Android 8.0+ reporting the same issue!

**Comment by aryanagarwal15** [comment]
I believe channel is not specified in the notification builder. check this out https://stackoverflow.com/questions/46341603/android-fcm-failed-to-post-notification-on-channel-my-channel-01
hope this solves the problem.

**Comment by aayushsingla** [comment]
@aryanagarwal15 yes, you are right. This should solve the problem.

**Comment by aryanagarwal15** [comment]
solved in #150

**Comment by aryanagarwal15** [comment]
@tanmaydixit this issue is resolved please mark accordingly
