### ISSUE TITLE
Problem with updating campus watch

### ISSUE THREAD

**Issue by aryanagarwal15** [MobileApplicationsClub/DoJMA#145]
Probably due to caching campus watch updates is getting delayed. Suggest removing firebase caching or making a realm database to pull from firebase and then showing data for campus watch.

**Comment by Rushi98** [comment]
@aryanagarwal15  How will removing firebase caching solve the issue?

**Comment by aryanagarwal15** [comment]
I'm asking to remove firebase caching. @Rushi98 once caching is removed and the whole campus watch reloads every time will make sure that the recent campus watch is visible at all times.

**Comment by Rushi98** [comment]
Firebase does sync every possible time even with caching enabled. Having caching enables us not to show empty data. The problem probably lies somewhere else.

**Comment by aryanagarwal15** [comment]
this is the problem with persistence only. I am pretty sure about this. Can simply fix it by refreshing list data.

**Comment by Rushi98** [comment]
closing as stale
