### ISSUE TITLE
Feature request: Send notification through Journalist App

### ISSUE THREAD

**Issue by aryanagarwal15** [MobileApplicationsClub/DoJMA#152]
@aayushsingla can you please add this functionality to the journalist app?

You just need to add a cloud function to read change in firebase database "notification" child and send notification when there is any change.

**Comment by aayushsingla** [comment]
@aryanagarwal15  I am really busy these days.How soon do you want this to get completed?

**Comment by aryanagarwal15** [comment]
@aayushsingla How about till this weekend. I don't think that it will take much time!

**Comment by aryanagarwal15** [comment]
I checked but the current solution to send notification through firebase does not work (at least for my device API 27). Please look into it.
