### ISSUE TITLE
Update Travis CI file

### ISSUE THREAD

**Issue by kukreja-vikramaditya** [MobileApplicationsClub/DoJMA#60]
Need to fix travis ci file

**Comment by hardik124** [comment]
What is the problem with Travis CI file ?

**Comment by kukreja-vikramaditya** [comment]
CI tests are failing at Travis. Please investigate the failures and find solution for the same

**Comment by hardik124** [comment]
@kukreja-vikramaditya  do we necessarily need to build using jdk-7 as well ? 
build with jdk-8 works fine after fixing the issues with permission , but 7 doesnt .

**Comment by kukreja-vikramaditya** [comment]
@hardik124 Yes do not remove jdk7. Fix issues for both 7 and 8. Check this sample .travis.yml http://pastebin.ubuntu.com/24388468/ . See the before_script and scripts section. The app should be run on the created emulator and be able to run the ./gradlew commands

**Comment by hardik124** [comment]
@kukreja-vikramaditya , build tools 25 requires jdk8 . Hence I dont think it will work with jdk 7 , or we have to downgrade our build tools . 
What do you think is the possible solutions ?

**Comment by kukreja-vikramaditya** [comment]
>build tools 25 requires jdk8 . Hence I dont think it will work with jdk 7

Please post the link from you are stating this.

**Comment by hardik124** [comment]
Although official Android release docs don't mention any Java version restrictions. I have encountered this issue when I tried to use jdk 8. 
Here are more such queries.

http://stackoverflow.com/questions/39116095/android-studio-buildtools-24-0-1-requires-java-1-8-or-above

https://teamtreehouse.com/community/getting-this-message-buildtools-2401-requires-java-18-or-above-current-jdk-version-is-16.

**Comment by kukreja-vikramaditya** [comment]
For `openjdk7`, it turns out that the dependencies in DoJMA app cannot be compiled for openjdk versions lesser than 52(8) but since travis doesn't support `openjdk8`, it is best that we continue with `oraclejdk8`.

Please resolve other issues of the file so that CIs are green.

**Comment by hardik124** [comment]
If i remove jdk7 , it works fine . Should i send a PR?

**Comment by kukreja-vikramaditya** [comment]
Yes send PR with remaining fixes as mentioned here 
>See the before_script and scripts section. The app should be run on the created emulator and be able to run the ./gradlew commands

**Comment by kukreja-vikramaditya** [comment]
Issue is resolved.
@hardik124 Please create new issue regarding LeakCanary failures ate discussed in #68
