### ISSUE TITLE
Load full screen view of images .

### ISSUE THREAD

**Issue by hardik124** [MobileApplicationsClub/DoJMA#67]
Currently mess menu is not not opened in full screen on clicking on it . A new feature should be added in order to enable users to open images in full screen and save and share them .

**Comment by hardik124** [comment]
@kukreja-vikramaditya  If this issue is valid , i would like to work on it.

**Comment by kukreja-vikramaditya** [comment]
Approved. Check old commits to see how this was done earlier

**Comment by hardik124** [comment]
@kukreja-vikramaditya , can we add a seperate activity to view images in full screen . 
It would look something like . 
![screenshot from 2017-04-23 01-25-57](https://cloud.githubusercontent.com/assets/6649948/25307767/9026f952-27c4-11e7-816e-a1623c20a693.png)

**Comment by kukreja-vikramaditya** [comment]
@yashsharan 
@shreyasnbhat 
@shubham-kumar1410 

Please share views on this

@hardik124 
I don't see a reason why this cannot be done in the existing activity using existing viewpager

**Comment by hardik124** [comment]
It could be. I just suggested this.
I will try to implement it using existing view pager.
