### ISSUE TITLE
Make FB page button in About Dojma.

### ISSUE THREAD

**Issue by tanmaydixit** [MobileApplicationsClub/DoJMA#81]
Put the fb page of DoJMA in About Dojma activity.

**Comment by Rushi98** [comment]
@tanmaydixit invalid (no nav drawer) ?

**Comment by HarshRaj0942** [comment]
on it.

**Comment by Rushi98** [comment]
I think this is invalid. @HarshRaj0942 you can take up #85

**Comment by aryanagarwal15** [comment]
@Rushi98 I believe there will a about dojma activity that would be accessible via three dot button to top right. Over there please put all social media buttons.

Links for the same are
Facebook - https://www.facebook.com/DoJMABITSGoa/
twitter - https://twitter.com/dojmabitsgoa
Youtube - https://www.youtube.com/channel/UCtO0OtOBQ40poBQpJZ8ZVuA

**Comment by Rushi98** [comment]
to be done in #85
