### ISSUE TITLE
Inshorts like campus watch

### ISSUE THREAD

**Issue by tanmaydixit** [MobileApplicationsClub/DoJMA#87]
App to have the campus watch inbuilt that can be shown as manner similar to what 
Inshorts is applying. 
The inshorts type filp/slide feature will be the challenge for which i recommend using a library(freely available).
The campus watch articles will be 50-70 words accompanying an image, 
and time stamp.(Basically 4 fields title, subtitle, imageUrl, timeStamp)
Currently this will be a new activity which will open up on the click of a button on the left of the top bar in the main activity.

**Comment by YashxD** [comment]
On it
I make this in a separate activity, right?

**Comment by tanmaydixit** [comment]
Yes, the button to open that activity will be on the left side of the toolbar(MainActivity)

**Comment by tanmaydixit** [comment]
Solved by @YashxD in #109
