### ISSUE TITLE
Remodeling the Herald Item View

### ISSUE THREAD

**Issue by tanmaydixit** [MobileApplicationsClub/DoJMA#89]
The new view will have the image rectangular on the top with the headline coming in below it.
```
-------------------
|                     |
|       image     |
|                     |
-------------------
Headline [1][2]
date
starting of the news 
with dot dot in the 
end....
```
[1] is the heart icon for favorites.
[2] is the share icon.

**Comment by aryanagarwal15** [comment]
![default](https://user-images.githubusercontent.com/28765515/41507284-638b7efc-724d-11e8-9f45-7262216cbec3.png)

Hey It will be good if we can make the layout of the recycler view exactly as mentioned above.
Also please remove the section of preview of article as that certainly is not required.

Above the newspaper icon in bottom right can be changed to heart icon and the three dots section can bring up menu to share.

The Rounded corners in the featured image should also stay.

Also the NDTV section can be replaced by clickable categories of that particular article.

**Comment by aryanagarwal15** [comment]
Since Nobody is assigned to this @tanmaydixit can you assign this to me. I may have a better view revamping the view.

I'll start working after it's assigned.

**Comment by Rushi98** [comment]
@aryanagarwal15 accept the collaborator invite to be assigned an issue.

**Comment by aryanagarwal15** [comment]
I have accepted the invitation.

**Comment by aryanagarwal15** [comment]
@tanmaydixit Please close this as this issue is resolved.
